id: dk.ehmi.eds
canonical: http://medcomehmi.dk/ig/eds
name: EHMI EDS IG
title: "DK EHMI Delivery Status (EDS)"
description: The DK EHMI Delivery Status (EDS)
status: draft # draft | active | retired | unknown
version: 1.0.1-draft
fhirVersion: 4.0.1
copyrightYear: 2025+
releaseLabel: draft # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
jurisdiction: urn:iso:std:iso:3166#DK "Denmark"
publisher:
  name: MedCom
  url: https://www.medcom.dk
  email: ehmi@medcom.dk

dependencies:
  hl7.fhir.dk.core: 3.4.0
  medcom.fhir.dk.core: 2.4.0
  medcom.fhir.dk.messaging: 3.0.0
  medcom.fhir.dk.terminology: 1.8.1
  dk.ehmi.terminology: 1.0.0-draft
  dk.ehmi.eer: 1.0.0-draft

parameters:
  apply-contact: true
  apply-publisher: true

menu:
  Home: index.html
  Profiles: profiles.html
  Use-cases: 
    EDS Use case 1: eds-use-case-1.html
    EDS Use case 2: eds-use-case-2.html
  Artifacts: artifacts.html
  Security: 
    Security-en: security-english.html
    Security-da: security-danish.html
  More:
    Table of Contents: toc.html
    Downloads: downloads.html
    Dependencies: dependencies.html

parameters:
  apply-version: false
  default-version: true
  apply-publisher: false
  default-publisher: true
  pin-canonicals: pin-multiples
  excludettl: true

